### ISSUE TITLE
Bad user 

### ISSUE THREAD

**Issue by Rasofex** [ryuJin25/Kde-Configs#1]
Hello. I really liked your KDE theme, but I'm new to using Linux, so could you describe how to install it all, and preferably in simple words. Thank you in advance.

**Comment by ryuJin25** [comment]
Alright, I will update this readme in couple of hours so you can install it :D

**Comment by ryuJin25** [comment]
> Hello. I really liked your KDE theme, but I'm new to using Linux, so could you describe how to install it all, and preferably in simple words. Thank you in advance.

Readme updated ;)
